// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: analisisLexicoLenguaje1.jflex

package com.mycompany.analizador;
import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;


@SuppressWarnings("fallthrough")
public class LexerFormulario implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int DENTRO_CADENA = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\0\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\3\23"+
    "\1\24\6\23\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\66\1\0\1\67\1\70\1\71"+
    "\1\0\1\72\1\73\1\74\1\75\1\76\1\77\1\100"+
    "\1\101\1\102\1\45\1\103\1\104\1\105\1\106\1\107"+
    "\1\110\1\45\1\111\1\112\1\113\1\114\1\45\1\115"+
    "\1\45\1\116\1\45\1\117\1\120\1\121\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\1\1\2\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\23\25\1\26\1\27\1\30\13\25\1\31\1\1\1\32"+
    "\1\33\1\34\1\33\1\35\1\0\1\36\6\0\1\37"+
    "\1\40\1\41\2\25\1\42\5\25\1\43\22\25\1\44"+
    "\11\25\1\45\6\0\1\16\3\0\7\25\1\46\7\25"+
    "\1\47\3\25\1\50\24\25\7\0\1\25\1\51\4\25"+
    "\1\52\2\25\1\53\1\54\7\25\1\55\6\25\1\56"+
    "\14\25\17\0\1\57\4\25\1\60\7\25\1\61\1\25"+
    "\1\62\1\63\5\25\1\64\10\25\1\65\2\66\14\0"+
    "\1\25\1\67\1\70\4\25\1\71\4\25\1\72\3\25"+
    "\1\73\1\74\2\25\1\75\1\76\1\25\1\77\1\100"+
    "\1\25\5\0\1\101\1\0\1\102\3\0\1\103\1\104"+
    "\5\25\1\105\2\25\1\106\1\107\1\25\1\110\1\25"+
    "\1\111\1\25\5\0\6\25\1\112\1\113\2\25\3\0"+
    "\10\25\3\0\1\25\1\114\2\25\1\115\7\25\1\116"+
    "\6\25\1\117\1\25\1\120\6\25\1\121\3\25\1\122"+
    "\2\25\1\123";

  private static int [] zzUnpackAction() {
    int [] result = new int[390];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\122\0\244\0\244\0\366\0\u0148\0\244\0\u019a"+
    "\0\u01ec\0\244\0\u023e\0\u0290\0\244\0\244\0\244\0\244"+
    "\0\244\0\244\0\u02e2\0\u0334\0\244\0\244\0\u0386\0\u03d8"+
    "\0\u042a\0\244\0\u047c\0\u04ce\0\u0520\0\u0572\0\u05c4\0\u0616"+
    "\0\u0668\0\u06ba\0\u070c\0\u075e\0\u07b0\0\u0802\0\u0854\0\u08a6"+
    "\0\u08f8\0\u094a\0\u099c\0\u09ee\0\u0a40\0\244\0\244\0\244"+
    "\0\u0a92\0\u0ae4\0\u0b36\0\u0b88\0\u0bda\0\u0c2c\0\u0c7e\0\u0cd0"+
    "\0\u0d22\0\u0d74\0\u0dc6\0\244\0\u0e18\0\244\0\u0e6a\0\244"+
    "\0\u0ebc\0\244\0\u0f0e\0\244\0\u0290\0\u0f60\0\u0fb2\0\u1004"+
    "\0\u1056\0\u10a8\0\244\0\244\0\244\0\u10fa\0\u114c\0\u119e"+
    "\0\u11f0\0\u1242\0\u1294\0\u12e6\0\u1338\0\u047c\0\u138a\0\u13dc"+
    "\0\u142e\0\u1480\0\u14d2\0\u1524\0\u1576\0\u15c8\0\u161a\0\u166c"+
    "\0\u16be\0\u1710\0\u1762\0\u17b4\0\u1806\0\u1858\0\u18aa\0\u18fc"+
    "\0\u047c\0\u194e\0\u19a0\0\u19f2\0\u1a44\0\u1a96\0\u1ae8\0\u1b3a"+
    "\0\u1b8c\0\u1bde\0\244\0\u1c30\0\u1c82\0\u1cd4\0\u1d26\0\u1d78"+
    "\0\u1dca\0\u1004\0\u1e1c\0\u1e6e\0\u1ec0\0\u1f12\0\u1f64\0\u1fb6"+
    "\0\u2008\0\u205a\0\u20ac\0\u20fe\0\u047c\0\u2150\0\u21a2\0\u21f4"+
    "\0\u2246\0\u2298\0\u22ea\0\u233c\0\u047c\0\u238e\0\u23e0\0\u2432"+
    "\0\u047c\0\u2484\0\u24d6\0\u2528\0\u257a\0\u25cc\0\u261e\0\u2670"+
    "\0\u26c2\0\u2714\0\u2766\0\u27b8\0\u280a\0\u285c\0\u28ae\0\u2900"+
    "\0\u2952\0\u29a4\0\u29f6\0\u2a48\0\u2a9a\0\u2aec\0\u2b3e\0\u2b90"+
    "\0\u2be2\0\u2c34\0\u2c86\0\u2cd8\0\u2d2a\0\u047c\0\u2d7c\0\u2dce"+
    "\0\u2e20\0\u2e72\0\u047c\0\u2ec4\0\u2f16\0\u047c\0\u047c\0\u2f68"+
    "\0\u2fba\0\u300c\0\u305e\0\u30b0\0\u3102\0\u3154\0\u047c\0\u31a6"+
    "\0\u31f8\0\u324a\0\u329c\0\u32ee\0\u3340\0\u047c\0\u3392\0\u33e4"+
    "\0\u3436\0\u3488\0\u34da\0\u352c\0\u357e\0\u35d0\0\u3622\0\u3674"+
    "\0\u36c6\0\u3718\0\u376a\0\u37bc\0\u380e\0\u3860\0\u38b2\0\u3904"+
    "\0\u3956\0\u39a8\0\u39fa\0\u3a4c\0\u3a9e\0\u3af0\0\u3b42\0\u3b94"+
    "\0\u3be6\0\u047c\0\u3c38\0\u3c8a\0\u3cdc\0\u3d2e\0\u047c\0\u3d80"+
    "\0\u3dd2\0\u3e24\0\u3e76\0\u3ec8\0\u3f1a\0\u3f6c\0\u047c\0\u3fbe"+
    "\0\u047c\0\u047c\0\u4010\0\u4062\0\u40b4\0\u4106\0\u4158\0\u047c"+
    "\0\u41aa\0\u41fc\0\u424e\0\u42a0\0\u42f2\0\u4344\0\u4396\0\u43e8"+
    "\0\u047c\0\244\0\u380e\0\u443a\0\u448c\0\u44de\0\u4530\0\u4582"+
    "\0\u45d4\0\u4626\0\u4678\0\u46ca\0\u471c\0\u476e\0\u47c0\0\u4812"+
    "\0\u047c\0\u047c\0\u4864\0\u48b6\0\u4908\0\u495a\0\u047c\0\u49ac"+
    "\0\u49fe\0\u4a50\0\u4aa2\0\u047c\0\u4af4\0\u4b46\0\u4b98\0\u047c"+
    "\0\u047c\0\u4bea\0\u4c3c\0\u047c\0\u047c\0\u4c8e\0\u047c\0\u047c"+
    "\0\u4ce0\0\u4d32\0\u4d84\0\u4dd6\0\u4e28\0\u4e7a\0\244\0\u4ecc"+
    "\0\244\0\u4f1e\0\u4f70\0\u4fc2\0\244\0\u047c\0\u5014\0\u5066"+
    "\0\u50b8\0\u510a\0\u515c\0\u047c\0\u51ae\0\u5200\0\u047c\0\u047c"+
    "\0\u5252\0\u047c\0\u52a4\0\u047c\0\u52f6\0\u5348\0\u539a\0\u53ec"+
    "\0\u543e\0\u5490\0\u54e2\0\u5534\0\u5586\0\u55d8\0\u562a\0\u567c"+
    "\0\u047c\0\u047c\0\u56ce\0\u5720\0\u5772\0\u57c4\0\u5816\0\u5868"+
    "\0\u58ba\0\u590c\0\u595e\0\u59b0\0\u5a02\0\u5a54\0\u5aa6\0\u5af8"+
    "\0\u5b4a\0\u5b9c\0\u5bee\0\u047c\0\u5c40\0\u5c92\0\u047c\0\u5ce4"+
    "\0\u5d36\0\u5d88\0\u5dda\0\u5e2c\0\u5e7e\0\u5ed0\0\u047c\0\u5f22"+
    "\0\u5f74\0\u5fc6\0\u6018\0\u606a\0\u60bc\0\u047c\0\u610e\0\u047c"+
    "\0\u6160\0\u61b2\0\u6204\0\u6256\0\u62a8\0\u62fa\0\u047c\0\u634c"+
    "\0\u639e\0\u63f0\0\u047c\0\u6442\0\u6494\0\u047c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[390];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\4\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\2\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\3\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\2\33\1\44\1\45\1\33\1\46"+
    "\1\47\1\33\1\50\1\51\1\52\1\33\1\53\1\54"+
    "\1\33\1\55\1\33\1\56\1\57\1\60\3\33\1\61"+
    "\1\62\1\63\2\33\1\64\1\65\1\33\1\66\1\33"+
    "\1\67\1\70\1\71\1\33\1\72\2\33\1\73\1\33"+
    "\1\74\1\75\1\76\6\77\1\100\24\77\1\101\66\77"+
    "\124\0\1\4\124\0\1\102\137\0\2\103\7\0\6\103"+
    "\30\0\6\103\22\0\2\11\1\4\1\5\116\11\12\0"+
    "\1\104\113\0\1\105\16\0\2\106\112\0\1\107\125\0"+
    "\1\110\1\0\2\24\101\0\1\111\16\0\2\112\3\0"+
    "\1\113\121\0\1\114\121\0\1\115\114\0\2\33\7\0"+
    "\32\33\3\0\26\33\26\0\2\33\7\0\13\33\1\116"+
    "\16\33\3\0\26\33\26\0\2\33\7\0\24\33\1\117"+
    "\5\33\3\0\26\33\26\0\2\33\7\0\16\33\1\120"+
    "\2\33\1\121\10\33\3\0\26\33\26\0\2\33\7\0"+
    "\13\33\1\122\16\33\3\0\26\33\26\0\2\33\7\0"+
    "\16\33\1\123\13\33\3\0\26\33\26\0\2\33\7\0"+
    "\21\33\1\124\10\33\3\0\26\33\26\0\2\33\7\0"+
    "\16\33\1\125\13\33\3\0\26\33\26\0\2\33\7\0"+
    "\5\33\1\126\24\33\3\0\26\33\26\0\2\33\7\0"+
    "\10\33\1\127\21\33\3\0\26\33\26\0\2\33\7\0"+
    "\16\33\1\130\5\33\1\131\5\33\3\0\26\33\26\0"+
    "\2\33\7\0\17\33\1\132\12\33\3\0\26\33\26\0"+
    "\2\33\7\0\24\33\1\133\5\33\3\0\26\33\26\0"+
    "\2\33\7\0\4\33\1\134\25\33\3\0\26\33\26\0"+
    "\2\33\7\0\1\135\3\33\1\136\5\33\1\137\17\33"+
    "\3\0\26\33\26\0\2\33\7\0\1\140\3\33\1\141"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\4\33\1\142"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\7\33\1\143"+
    "\22\33\3\0\26\33\26\0\2\33\7\0\4\33\1\144"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\32\33\3\0"+
    "\16\33\1\145\7\33\26\0\2\33\7\0\32\33\3\0"+
    "\20\33\1\146\5\33\26\0\2\33\7\0\32\33\3\0"+
    "\13\33\1\147\12\33\26\0\2\33\7\0\32\33\3\0"+
    "\5\33\1\150\20\33\26\0\2\33\7\0\32\33\3\0"+
    "\15\33\1\151\10\33\26\0\2\33\7\0\32\33\3\0"+
    "\1\33\1\152\24\33\26\0\2\33\7\0\32\33\3\0"+
    "\23\33\1\153\2\33\26\0\2\33\7\0\32\33\3\0"+
    "\17\33\1\154\1\155\5\33\26\0\2\33\7\0\32\33"+
    "\3\0\16\33\1\156\7\33\26\0\2\33\7\0\32\33"+
    "\3\0\17\33\1\157\2\33\1\160\3\33\26\0\2\33"+
    "\7\0\32\33\3\0\10\33\1\161\1\162\14\33\123\0"+
    "\1\163\1\0\6\77\1\0\24\77\1\0\66\77\66\0"+
    "\1\164\56\0\2\165\7\0\6\165\30\0\6\165\26\0"+
    "\1\166\12\0\1\167\1\0\1\170\1\0\2\106\75\0"+
    "\15\107\1\171\104\107\23\0\2\172\101\0\1\111\16\0"+
    "\2\112\101\0\1\173\12\0\1\174\1\0\1\175\1\0"+
    "\2\112\120\0\2\33\7\0\1\176\23\33\1\177\5\33"+
    "\3\0\26\33\26\0\2\33\7\0\21\33\1\200\10\33"+
    "\3\0\26\33\26\0\2\33\7\0\23\33\1\201\1\202"+
    "\5\33\3\0\26\33\26\0\2\33\7\0\16\33\1\203"+
    "\13\33\3\0\26\33\26\0\2\33\7\0\22\33\1\204"+
    "\7\33\3\0\26\33\26\0\2\33\7\0\21\33\1\205"+
    "\10\33\3\0\26\33\26\0\2\33\7\0\4\33\1\206"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\21\33\1\207"+
    "\10\33\3\0\26\33\26\0\2\33\7\0\15\33\1\210"+
    "\14\33\3\0\26\33\26\0\2\33\7\0\15\33\1\211"+
    "\14\33\3\0\26\33\26\0\2\33\7\0\13\33\1\212"+
    "\16\33\3\0\26\33\26\0\2\33\7\0\4\33\1\213"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\21\33\1\214"+
    "\10\33\3\0\26\33\26\0\2\33\7\0\3\33\1\215"+
    "\26\33\3\0\26\33\26\0\2\33\7\0\15\33\1\216"+
    "\14\33\3\0\26\33\26\0\2\33\7\0\2\33\1\217"+
    "\10\33\1\220\16\33\3\0\26\33\26\0\2\33\7\0"+
    "\30\33\1\221\1\33\3\0\26\33\26\0\2\33\7\0"+
    "\1\33\1\222\30\33\3\0\26\33\26\0\2\33\7\0"+
    "\27\33\1\223\2\33\3\0\26\33\26\0\2\33\7\0"+
    "\21\33\1\224\10\33\3\0\26\33\26\0\2\33\7\0"+
    "\10\33\1\225\21\33\3\0\26\33\26\0\2\33\7\0"+
    "\13\33\1\226\16\33\3\0\26\33\26\0\2\33\7\0"+
    "\32\33\3\0\15\33\1\227\2\33\1\230\5\33\26\0"+
    "\2\33\7\0\32\33\3\0\1\33\1\231\24\33\26\0"+
    "\2\33\7\0\32\33\3\0\5\33\1\232\20\33\26\0"+
    "\2\33\7\0\32\33\3\0\11\33\1\233\14\33\26\0"+
    "\2\33\7\0\32\33\3\0\2\33\1\234\23\33\26\0"+
    "\2\33\7\0\32\33\3\0\14\33\1\235\11\33\26\0"+
    "\2\33\7\0\32\33\3\0\22\33\1\236\3\33\26\0"+
    "\2\33\7\0\32\33\3\0\11\33\1\237\14\33\26\0"+
    "\2\33\7\0\32\33\3\0\11\33\1\240\14\33\26\0"+
    "\2\33\7\0\32\33\3\0\5\33\1\241\20\33\26\0"+
    "\2\33\7\0\32\33\3\0\20\33\1\242\4\33\1\243"+
    "\26\0\2\33\7\0\32\33\3\0\16\33\1\244\7\33"+
    "\26\0\2\33\7\0\32\33\3\0\4\33\1\245\21\33"+
    "\30\0\1\246\1\0\1\247\115\0\2\250\7\0\6\250"+
    "\30\0\6\250\26\0\1\166\12\0\1\167\106\0\1\167"+
    "\16\0\2\251\120\0\2\252\75\0\15\107\1\171\4\107"+
    "\1\4\77\107\4\0\1\173\12\0\1\174\106\0\1\174"+
    "\16\0\2\253\120\0\2\254\120\0\2\33\7\0\2\33"+
    "\1\255\27\33\3\0\26\33\26\0\2\33\7\0\4\33"+
    "\1\256\25\33\3\0\26\33\26\0\2\33\7\0\22\33"+
    "\1\257\7\33\3\0\26\33\26\0\2\33\7\0\23\33"+
    "\1\260\6\33\3\0\26\33\26\0\2\33\7\0\1\33"+
    "\1\261\30\33\3\0\26\33\26\0\2\33\7\0\17\33"+
    "\1\262\12\33\3\0\26\33\26\0\2\33\7\0\4\33"+
    "\1\263\25\33\3\0\26\33\26\0\2\33\7\0\4\33"+
    "\1\264\25\33\3\0\26\33\26\0\2\33\7\0\10\33"+
    "\1\265\21\33\3\0\26\33\26\0\2\33\7\0\4\33"+
    "\1\266\25\33\3\0\26\33\26\0\2\33\7\0\16\33"+
    "\1\267\13\33\3\0\26\33\26\0\2\33\7\0\23\33"+
    "\1\270\6\33\3\0\26\33\26\0\2\33\7\0\15\33"+
    "\1\271\14\33\3\0\26\33\26\0\2\33\7\0\17\33"+
    "\1\272\12\33\3\0\26\33\26\0\2\33\7\0\22\33"+
    "\1\273\7\33\3\0\26\33\26\0\2\33\7\0\23\33"+
    "\1\274\6\33\3\0\26\33\26\0\2\33\7\0\4\33"+
    "\1\275\25\33\3\0\26\33\26\0\2\33\7\0\13\33"+
    "\1\276\16\33\3\0\26\33\26\0\2\33\7\0\23\33"+
    "\1\277\6\33\3\0\26\33\26\0\2\33\7\0\23\33"+
    "\1\300\6\33\3\0\26\33\26\0\2\33\7\0\13\33"+
    "\1\301\7\33\1\302\6\33\3\0\26\33\26\0\2\33"+
    "\7\0\13\33\1\303\16\33\3\0\26\33\26\0\2\33"+
    "\7\0\32\33\3\0\22\33\1\304\3\33\26\0\2\33"+
    "\7\0\32\33\3\0\20\33\1\305\5\33\26\0\2\33"+
    "\7\0\32\33\3\0\24\33\1\306\1\33\26\0\2\33"+
    "\7\0\32\33\3\0\14\33\1\307\11\33\26\0\2\33"+
    "\7\0\32\33\3\0\7\33\1\310\16\33\26\0\2\33"+
    "\7\0\32\33\3\0\5\33\1\311\20\33\26\0\2\33"+
    "\7\0\32\33\3\0\2\33\1\312\23\33\26\0\2\33"+
    "\7\0\32\33\3\0\11\33\1\313\14\33\26\0\2\33"+
    "\7\0\32\33\3\0\5\33\1\314\20\33\26\0\2\33"+
    "\7\0\32\33\3\0\15\33\1\315\10\33\26\0\2\33"+
    "\7\0\32\33\3\0\3\33\1\316\22\33\26\0\2\33"+
    "\7\0\32\33\3\0\11\33\1\317\14\33\26\0\2\33"+
    "\7\0\32\33\3\0\13\33\1\320\12\33\26\0\2\33"+
    "\7\0\32\33\3\0\1\321\25\33\26\0\2\33\7\0"+
    "\32\33\3\0\22\33\1\322\3\33\16\0\1\323\1\324"+
    "\52\0\1\325\1\326\3\0\1\327\4\0\1\330\10\0"+
    "\1\331\33\0\1\332\2\0\1\247\115\0\2\333\7\0"+
    "\6\333\30\0\6\333\26\0\1\334\12\0\1\335\1\0"+
    "\1\336\1\0\2\251\101\0\1\166\12\0\1\167\3\0"+
    "\2\252\101\0\1\337\12\0\1\340\1\0\1\341\1\0"+
    "\2\253\101\0\1\173\12\0\1\174\3\0\2\254\120\0"+
    "\2\33\7\0\12\33\1\342\17\33\3\0\26\33\26\0"+
    "\2\33\7\0\10\33\1\343\21\33\3\0\26\33\26\0"+
    "\2\33\7\0\4\33\1\344\25\33\3\0\26\33\26\0"+
    "\2\33\7\0\13\33\1\345\16\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\1\346\25\33\26\0\2\33"+
    "\7\0\15\33\1\347\14\33\3\0\26\33\26\0\2\33"+
    "\7\0\31\33\1\350\3\0\26\33\26\0\2\33\7\0"+
    "\10\33\1\351\21\33\3\0\26\33\26\0\2\33\7\0"+
    "\32\33\3\0\1\352\25\33\26\0\2\33\7\0\13\33"+
    "\1\353\16\33\3\0\26\33\26\0\2\33\7\0\32\33"+
    "\3\0\1\354\25\33\26\0\2\33\7\0\10\33\1\355"+
    "\21\33\3\0\26\33\26\0\2\33\7\0\2\33\1\356"+
    "\27\33\3\0\26\33\26\0\2\33\7\0\4\33\1\357"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\10\33\1\360"+
    "\21\33\3\0\26\33\26\0\2\33\7\0\4\33\1\361"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\4\33\1\362"+
    "\25\33\3\0\26\33\26\0\2\33\7\0\16\33\1\363"+
    "\13\33\3\0\26\33\26\0\2\33\7\0\32\33\3\0"+
    "\5\33\1\364\20\33\26\0\2\33\7\0\32\33\3\0"+
    "\5\33\1\365\20\33\26\0\2\33\7\0\32\33\3\0"+
    "\5\33\1\366\20\33\26\0\2\33\7\0\32\33\3\0"+
    "\10\33\1\367\15\33\26\0\2\33\7\0\32\33\3\0"+
    "\13\33\1\370\12\33\26\0\2\33\7\0\32\33\3\0"+
    "\5\33\1\371\20\33\26\0\2\33\7\0\32\33\3\0"+
    "\16\33\1\372\7\33\26\0\2\33\7\0\32\33\3\0"+
    "\15\33\1\373\10\33\26\0\2\33\7\0\32\33\3\0"+
    "\22\33\1\374\3\33\26\0\2\33\7\0\32\33\3\0"+
    "\11\33\1\375\14\33\26\0\2\33\7\0\32\33\3\0"+
    "\15\33\1\376\10\33\26\0\2\33\7\0\32\33\3\0"+
    "\5\33\1\377\20\33\26\0\2\33\7\0\32\33\3\0"+
    "\11\33\1\u0100\14\33\26\0\2\33\7\0\32\33\3\0"+
    "\10\33\1\u0101\15\33\16\0\1\323\53\0\1\u0102\46\0"+
    "\1\324\52\0\1\u0102\121\0\1\u0103\122\0\1\u0104\123\0"+
    "\1\u0105\125\0\1\u0106\115\0\1\u0107\3\0\1\u0108\6\0"+
    "\1\u0109\5\0\1\u010a\32\0\1\332\42\0\1\u0102\55\0"+
    "\2\u010b\7\0\6\u010b\30\0\6\u010b\26\0\1\334\12\0"+
    "\1\335\106\0\1\335\16\0\2\u010c\120\0\2\u010d\101\0"+
    "\1\337\12\0\1\340\106\0\1\340\16\0\2\u010e\120\0"+
    "\2\u010f\120\0\2\33\7\0\25\33\1\u0110\4\33\3\0"+
    "\26\33\26\0\2\33\7\0\3\33\1\u0111\26\33\3\0"+
    "\26\33\26\0\2\33\7\0\4\33\1\u0112\25\33\3\0"+
    "\26\33\26\0\2\33\7\0\20\33\1\u0113\11\33\3\0"+
    "\26\33\26\0\2\33\7\0\16\33\1\u0114\13\33\3\0"+
    "\26\33\26\0\2\33\7\0\17\33\1\u0115\12\33\3\0"+
    "\26\33\26\0\2\33\7\0\20\33\1\u0116\11\33\3\0"+
    "\26\33\26\0\2\33\7\0\4\33\1\u0117\25\33\3\0"+
    "\26\33\26\0\2\33\7\0\22\33\1\u0118\7\33\3\0"+
    "\26\33\26\0\2\33\7\0\16\33\1\u0119\13\33\3\0"+
    "\26\33\26\0\2\33\7\0\23\33\1\u011a\6\33\3\0"+
    "\26\33\26\0\2\33\7\0\2\33\1\u011b\27\33\3\0"+
    "\26\33\26\0\2\33\7\0\26\33\1\u011c\3\33\3\0"+
    "\26\33\26\0\2\33\7\0\32\33\3\0\15\33\1\u011d"+
    "\10\33\26\0\2\33\7\0\32\33\3\0\3\33\1\u011e"+
    "\22\33\26\0\2\33\7\0\32\33\3\0\15\33\1\u011f"+
    "\10\33\26\0\2\33\7\0\32\33\3\0\22\33\1\u0120"+
    "\3\33\26\0\2\33\7\0\32\33\3\0\20\33\1\u0121"+
    "\5\33\26\0\2\33\7\0\32\33\3\0\15\33\1\u0122"+
    "\10\33\26\0\2\33\7\0\32\33\3\0\22\33\1\u0123"+
    "\3\33\26\0\2\33\7\0\27\33\1\u0124\1\u0125\1\33"+
    "\3\0\26\33\26\0\2\33\7\0\32\33\3\0\1\33"+
    "\1\u0126\24\33\26\0\2\33\7\0\32\33\3\0\7\33"+
    "\1\u0127\16\33\26\0\2\33\7\0\32\33\3\0\21\33"+
    "\1\u0128\4\33\26\0\2\33\7\0\32\33\3\0\21\33"+
    "\1\u0129\4\33\30\0\1\u012a\207\0\1\u0104\100\0\1\u012b"+
    "\124\0\1\u0104\135\0\1\u012c\112\0\1\u012d\111\0\1\u012e"+
    "\52\0\2\u012f\7\0\6\u012f\30\0\6\u012f\26\0\1\u0130"+
    "\7\0\1\u0131\4\0\1\u0132\1\0\2\u010c\101\0\1\334"+
    "\12\0\1\335\3\0\2\u010d\101\0\1\u0133\14\0\1\u0134"+
    "\1\0\2\u010e\4\0\1\u0135\74\0\1\337\12\0\1\340"+
    "\3\0\2\u010f\120\0\2\33\7\0\4\33\1\u0136\25\33"+
    "\3\0\26\33\26\0\2\33\7\0\24\33\1\u0137\5\33"+
    "\3\0\26\33\26\0\2\33\7\0\15\33\1\u0138\14\33"+
    "\3\0\26\33\26\0\2\33\7\0\13\33\1\u0139\16\33"+
    "\3\0\26\33\26\0\2\33\7\0\24\33\1\u013a\5\33"+
    "\3\0\26\33\26\0\2\33\7\0\4\33\1\u013b\25\33"+
    "\3\0\26\33\26\0\2\33\7\0\15\33\1\u013c\14\33"+
    "\3\0\26\33\26\0\2\33\7\0\32\33\3\0\1\u013d"+
    "\25\33\26\0\2\33\7\0\1\u013e\31\33\3\0\26\33"+
    "\26\0\2\33\7\0\32\33\3\0\22\33\1\u013f\3\33"+
    "\26\0\2\33\7\0\32\33\3\0\22\33\1\u0140\3\33"+
    "\26\0\2\33\7\0\32\33\3\0\22\33\1\u0141\3\33"+
    "\26\0\2\33\7\0\32\33\3\0\21\33\1\u0142\4\33"+
    "\26\0\2\33\7\0\32\33\3\0\1\33\1\u0143\24\33"+
    "\26\0\2\33\7\0\32\33\3\0\13\33\1\u0144\12\33"+
    "\26\0\2\33\7\0\32\33\3\0\1\u0145\25\33\72\0"+
    "\1\u0102\143\0\1\u0105\112\0\1\u0146\123\0\1\u0147\126\0"+
    "\1\u0148\14\0\1\u0130\7\0\1\u0131\130\0\2\u0149\101\0"+
    "\1\u0133\24\0\1\u0135\113\0\2\u014a\120\0\2\33\7\0"+
    "\4\33\1\u014b\25\33\3\0\26\33\26\0\2\33\7\0"+
    "\23\33\1\u014c\6\33\3\0\26\33\26\0\2\33\7\0"+
    "\4\33\1\u014d\25\33\3\0\26\33\26\0\2\33\7\0"+
    "\4\33\1\u014e\25\33\3\0\26\33\26\0\2\33\7\0"+
    "\21\33\1\u014f\10\33\3\0\26\33\26\0\2\33\7\0"+
    "\20\33\1\u0150\11\33\3\0\26\33\26\0\2\33\7\0"+
    "\13\33\1\u0151\16\33\3\0\26\33\26\0\2\33\7\0"+
    "\32\33\3\0\21\33\1\u0152\4\33\26\0\2\33\7\0"+
    "\32\33\3\0\22\33\1\u0153\3\33\26\0\2\33\7\0"+
    "\32\33\3\0\22\33\1\u0154\3\33\112\0\1\u0155\110\0"+
    "\1\u0104\43\0\1\u0156\4\0\1\u0157\100\0\1\u0130\7\0"+
    "\1\u0131\6\0\2\u0149\101\0\1\u0133\16\0\2\u014a\4\0"+
    "\1\u0135\113\0\2\33\7\0\22\33\1\u0158\7\33\3\0"+
    "\26\33\26\0\2\33\7\0\1\u0159\31\33\3\0\26\33"+
    "\26\0\2\33\7\0\32\33\3\0\1\u015a\25\33\26\0"+
    "\2\33\7\0\22\33\1\u015b\7\33\3\0\26\33\26\0"+
    "\2\33\7\0\10\33\1\u015c\21\33\3\0\26\33\26\0"+
    "\2\33\7\0\24\33\1\u015d\5\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\11\33\1\u015e\14\33\26\0"+
    "\2\33\7\0\32\33\3\0\10\33\1\u015f\15\33\117\0"+
    "\1\u0160\30\0\2\u0161\120\0\2\u0162\42\0\1\u0102\55\0"+
    "\2\33\7\0\23\33\1\u0163\6\33\3\0\26\33\26\0"+
    "\2\33\7\0\13\33\1\u0164\16\33\3\0\26\33\26\0"+
    "\2\33\7\0\20\33\1\u0165\11\33\3\0\26\33\26\0"+
    "\2\33\7\0\23\33\1\u0166\6\33\3\0\26\33\26\0"+
    "\2\33\7\0\5\33\1\u0167\24\33\3\0\26\33\26\0"+
    "\2\33\7\0\4\33\1\u0168\25\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\16\33\1\u0169\7\33\26\0"+
    "\2\33\7\0\32\33\3\0\1\33\1\u016a\24\33\115\0"+
    "\1\u0104\27\0\1\u0104\2\0\2\u0161\120\0\2\u0162\1\u012a"+
    "\117\0\2\33\7\0\10\33\1\u016b\21\33\3\0\26\33"+
    "\26\0\2\33\7\0\24\33\1\u016c\5\33\3\0\26\33"+
    "\26\0\2\33\7\0\10\33\1\u016d\21\33\3\0\26\33"+
    "\26\0\2\33\7\0\22\33\1\u016e\7\33\3\0\26\33"+
    "\26\0\2\33\7\0\32\33\3\0\15\33\1\u016f\10\33"+
    "\26\0\2\33\7\0\32\33\3\0\22\33\1\u0170\3\33"+
    "\26\0\2\33\7\0\16\33\1\u0171\13\33\3\0\26\33"+
    "\26\0\2\33\7\0\4\33\1\u0172\25\33\3\0\26\33"+
    "\26\0\2\33\7\0\16\33\1\u0173\13\33\3\0\26\33"+
    "\26\0\2\33\7\0\23\33\1\u0174\6\33\3\0\26\33"+
    "\26\0\2\33\7\0\32\33\3\0\1\u0175\25\33\26\0"+
    "\2\33\7\0\15\33\1\u0176\14\33\3\0\26\33\26\0"+
    "\2\33\7\0\22\33\1\u0177\7\33\3\0\26\33\26\0"+
    "\2\33\7\0\15\33\1\u0178\14\33\3\0\26\33\26\0"+
    "\2\33\7\0\10\33\1\u0179\21\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\17\33\1\u017a\6\33\26\0"+
    "\2\33\7\0\23\33\1\u017b\6\33\3\0\26\33\26\0"+
    "\2\33\7\0\16\33\1\u017c\13\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\16\33\1\u017d\7\33\26\0"+
    "\2\33\7\0\10\33\1\u017e\21\33\3\0\26\33\26\0"+
    "\2\33\7\0\15\33\1\u017f\14\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\12\33\1\u0180\13\33\26\0"+
    "\2\33\7\0\16\33\1\u0181\13\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\5\33\1\u0182\20\33\26\0"+
    "\2\33\7\0\15\33\1\u0183\14\33\3\0\26\33\26\0"+
    "\2\33\7\0\32\33\3\0\14\33\1\u0184\11\33\26\0"+
    "\2\33\7\0\32\33\3\0\16\33\1\u0185\7\33\26\0"+
    "\2\33\7\0\32\33\3\0\15\33\1\u0186\10\33\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[25830];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\2\1\1\11\2\1\1\11\2\1\6\11"+
    "\2\1\2\11\3\1\1\11\23\1\3\11\13\1\1\11"+
    "\1\1\1\11\1\1\1\11\1\1\1\11\1\0\1\11"+
    "\6\0\3\11\45\1\1\11\6\0\1\1\3\0\50\1"+
    "\7\0\46\1\17\0\40\1\1\11\1\1\14\0\32\1"+
    "\5\0\1\11\1\0\1\11\3\0\1\11\20\1\5\0"+
    "\12\1\3\0\10\1\3\0\44\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[390];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private List<ErrorLexico> errores = new ArrayList<>();

    public List<ErrorLexico> getErrores() {
        return errores;
    }

    private Symbol symbol(int tipo) {
        return new Symbol(tipo, yyline + 1, yycolumn + 1);
    }

    private Symbol symbol(int tipo, Object valor) {
        return new Symbol(tipo, yyline + 1, yycolumn + 1, valor);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerFormulario(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return new Symbol(sym.EOF, yyline + 1, yycolumn + 1, "EOF");
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { errores.add(new ErrorLexico("Símbolo no reconocido: " + yytext(), yyline, yycolumn));
            }
          // fall through
          case 84: break;
          case 2:
            { 
            }
          // fall through
          case 85: break;
          case 3:
            { return symbol(sym.NOT, yytext());
            }
          // fall through
          case 86: break;
          case 4:
            { yybegin(DENTRO_CADENA); return symbol(sym.COMILLA, yytext());
            }
          // fall through
          case 87: break;
          case 5:
            { return symbol(sym.MODULO, yytext());
            }
          // fall through
          case 88: break;
          case 6:
            { return symbol(sym.PAR_IZQ, yytext());
            }
          // fall through
          case 89: break;
          case 7:
            { return symbol(sym.PAR_DER, yytext());
            }
          // fall through
          case 90: break;
          case 8:
            { return symbol(sym.POR, yytext());
            }
          // fall through
          case 91: break;
          case 9:
            { return symbol(sym.MAS, yytext());
            }
          // fall through
          case 92: break;
          case 10:
            { return symbol(sym.COMA, yytext());
            }
          // fall through
          case 93: break;
          case 11:
            { return symbol(sym.MENOS, yytext());
            }
          // fall through
          case 94: break;
          case 12:
            { return symbol(sym.PUNTO, yytext());
            }
          // fall through
          case 95: break;
          case 13:
            { return symbol(sym.DIV, yytext());
            }
          // fall through
          case 96: break;
          case 14:
            { return symbol(sym.NUMBER, Double.parseDouble(yytext()));
            }
          // fall through
          case 97: break;
          case 15:
            { return symbol(sym.DOS_PUNTOS, yytext());
            }
          // fall through
          case 98: break;
          case 16:
            { return symbol(sym.PUNTO_COMA, yytext());
            }
          // fall through
          case 99: break;
          case 17:
            { return symbol(sym.MENOR, yytext());
            }
          // fall through
          case 100: break;
          case 18:
            { return symbol(sym.ASIGNACION, yytext());
            }
          // fall through
          case 101: break;
          case 19:
            { return symbol(sym.MAYOR, yytext());
            }
          // fall through
          case 102: break;
          case 20:
            { return symbol(sym.COMODIN, yytext());
            }
          // fall through
          case 103: break;
          case 21:
            { return symbol(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 104: break;
          case 22:
            { return symbol(sym.COR_IZQ, yytext());
            }
          // fall through
          case 105: break;
          case 23:
            { return symbol(sym.COR_DER, yytext());
            }
          // fall through
          case 106: break;
          case 24:
            { return symbol(sym.POTENCIA, yytext());
            }
          // fall through
          case 107: break;
          case 25:
            { return symbol(sym.LLA_IZQ, yytext());
            }
          // fall through
          case 108: break;
          case 26:
            { return symbol(sym.LLA_DER, yytext());
            }
          // fall through
          case 109: break;
          case 27:
            { return symbol(sym.TEXTO_PLANO, yytext());
            }
          // fall through
          case 110: break;
          case 28:
            { yybegin(YYINITIAL); return symbol(sym.COMILLA, yytext());
            }
          // fall through
          case 111: break;
          case 29:
            { return symbol(sym.DIFERENTE, yytext());
            }
          // fall through
          case 112: break;
          case 30:
            { return symbol(sym.AND, yytext());
            }
          // fall through
          case 113: break;
          case 31:
            { return symbol(sym.MENOR_IGUAL, yytext());
            }
          // fall through
          case 114: break;
          case 32:
            { return symbol(sym.IGUALDAD, yytext());
            }
          // fall through
          case 115: break;
          case 33:
            { return symbol(sym.MAYOR_IGUAL, yytext());
            }
          // fall through
          case 116: break;
          case 34:
            { return symbol(sym.DO, yytext());
            }
          // fall through
          case 117: break;
          case 35:
            { return symbol(sym.IF, yytext());
            }
          // fall through
          case 118: break;
          case 36:
            { return symbol(sym.IN, yytext());
            }
          // fall through
          case 119: break;
          case 37:
            { return symbol(sym.OR, yytext());
            }
          // fall through
          case 120: break;
          case 38:
            { return symbol(sym.FOR, yytext());
            }
          // fall through
          case 121: break;
          case 39:
            { return symbol(sym.RED, yytext());
            }
          // fall through
          case 122: break;
          case 40:
            { return symbol(sym.SKY, yytext());
            }
          // fall through
          case 123: break;
          case 41:
            { return symbol(sym.BLUE, yytext());
            }
          // fall through
          case 124: break;
          case 42:
            { return symbol(sym.ELSE, yytext());
            }
          // fall through
          case 125: break;
          case 43:
            { return symbol(sym.LINE, yytext());
            }
          // fall through
          case 126: break;
          case 44:
            { return symbol(sym.MONO, yytext());
            }
          // fall through
          case 127: break;
          case 45:
            { return symbol(sym.TEXT, yytext());
            }
          // fall through
          case 128: break;
          case 46:
            { return symbol(sym.DRAW, yytext());
            }
          // fall through
          case 129: break;
          case 47:
            { return symbol(sym.BLACK, yytext());
            }
          // fall through
          case 130: break;
          case 48:
            { return symbol(sym.GREEN, yytext());
            }
          // fall through
          case 131: break;
          case 49:
            { return symbol(sym.TABLE, yytext());
            }
          // fall through
          case 132: break;
          case 50:
            { return symbol(sym.WHILE, yytext());
            }
          // fall through
          case 133: break;
          case 51:
            { return symbol(sym.WHITE, yytext());
            }
          // fall through
          case 134: break;
          case 52:
            { return symbol(sym.LABEL, yytext());
            }
          // fall through
          case 135: break;
          case 53:
            { return symbol(sym.WIDTH, yytext());
            }
          // fall through
          case 136: break;
          case 54:
            { return symbol(sym.EMOJI, yytext());
            }
          // fall through
          case 137: break;
          case 55:
            { return symbol(sym.DOTTED, yytext());
            }
          // fall through
          case 138: break;
          case 56:
            { return symbol(sym.DOUBLE, yytext());
            }
          // fall through
          case 139: break;
          case 57:
            { return symbol(sym.PURPLE, yytext());
            }
          // fall through
          case 140: break;
          case 58:
            { return symbol(sym.YELLOW, yytext());
            }
          // fall through
          case 141: break;
          case 59:
            { return symbol(sym.HEIGHT, yytext());
            }
          // fall through
          case 142: break;
          case 60:
            { return symbol(sym.TYPE_NUMBER, yytext());
            }
          // fall through
          case 143: break;
          case 61:
            { return symbol(sym.POINTX, yytext());
            }
          // fall through
          case 144: break;
          case 62:
            { return symbol(sym.POINTY, yytext());
            }
          // fall through
          case 145: break;
          case 63:
            { return symbol(sym.TYPE_STRING, yytext());
            }
          // fall through
          case 146: break;
          case 64:
            { return symbol(sym.STYLES, yytext());
            }
          // fall through
          case 147: break;
          case 65:
            { return symbol(sym.COLOR_HEX, yytext());
            }
          // fall through
          case 148: break;
          case 66:
            { return symbol(sym.COLOR_RGB, yytext());
            }
          // fall through
          case 149: break;
          case 67:
            { return symbol(sym.COLOR_HSL, yytext());
            }
          // fall through
          case 150: break;
          case 68:
            { return symbol(sym.CURSIVE, yytext());
            }
          // fall through
          case 151: break;
          case 69:
            { return symbol(sym.SECTION, yytext());
            }
          // fall through
          case 152: break;
          case 70:
            { return symbol(sym.CONTENT, yytext());
            }
          // fall through
          case 153: break;
          case 71:
            { return symbol(sym.CORRECT, yytext());
            }
          // fall through
          case 154: break;
          case 72:
            { return symbol(sym.OPTIONS, yytext());
            }
          // fall through
          case 155: break;
          case 73:
            { return symbol(sym.TYPE_SPECIAL, yytext());
            }
          // fall through
          case 156: break;
          case 74:
            { return symbol(sym.VERTICAL, yytext());
            }
          // fall through
          case 157: break;
          case 75:
            { return symbol(sym.ELEMENTS, yytext());
            }
          // fall through
          case 158: break;
          case 76:
            { return symbol(sym.HORIZONTAL, yytext());
            }
          // fall through
          case 159: break;
          case 77:
            { return symbol(sym.SANS_SERIF, yytext());
            }
          // fall through
          case 160: break;
          case 78:
            { return symbol(sym.ORIENTATION, yytext());
            }
          // fall through
          case 161: break;
          case 79:
            { return symbol(sym.DROP_QUESTION, yytext());
            }
          // fall through
          case 162: break;
          case 80:
            { return symbol(sym.OPEN_QUESTION, yytext());
            }
          // fall through
          case 163: break;
          case 81:
            { return symbol(sym.SELECT_QUESTION, yytext());
            }
          // fall through
          case 164: break;
          case 82:
            { return symbol(sym.MULTIPLE_QUESTION, yytext());
            }
          // fall through
          case 165: break;
          case 83:
            { return symbol(sym.WHO_IS_THAT_POKEMON, yytext());
            }
          // fall through
          case 166: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
