
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.analizador;

import java_cup.runtime.*;
import java.util.List;
import java.util.ArrayList;
import com.mycompany.analizador.ErrorSintactico;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserPKM extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return symPKM.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserPKM() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserPKM(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserPKM(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\115\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\035\005" +
    "\000\002\035\004\000\002\036\004\000\002\036\004\000" +
    "\002\036\003\000\002\036\003\000\002\003\030\000\002" +
    "\005\003\000\002\005\003\000\002\005\002\000\002\004" +
    "\003\000\002\004\003\000\002\004\002\000\002\006\011" +
    "\000\002\007\004\000\002\007\003\000\002\010\007\000" +
    "\002\010\007\000\002\010\007\000\002\010\007\000\002" +
    "\010\007\000\002\010\015\000\002\017\003\000\002\017" +
    "\003\000\002\017\003\000\002\017\003\000\002\015\003" +
    "\000\002\015\003\000\002\015\003\000\002\016\003\000" +
    "\002\016\003\000\002\016\003\000\002\014\003\000\002" +
    "\014\003\000\002\011\003\000\002\011\002\000\002\012" +
    "\004\000\002\012\003\000\002\013\003\000\002\013\003" +
    "\000\002\013\003\000\002\013\003\000\002\013\003\000" +
    "\002\013\003\000\002\020\032\000\002\020\031\000\002" +
    "\021\020\000\002\021\017\000\002\022\004\000\002\022" +
    "\003\000\002\023\011\000\002\024\004\000\002\024\003" +
    "\000\002\025\011\000\002\026\013\000\002\026\017\000" +
    "\002\026\016\000\002\027\021\000\002\027\025\000\002" +
    "\027\024\000\002\030\021\000\002\030\025\000\002\030" +
    "\024\000\002\031\023\000\002\031\027\000\002\031\026" +
    "\000\002\032\005\000\002\032\003\000\002\033\003\000" +
    "\002\033\002\000\002\034\005\000\002\034\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u010a\000\004\004\004\001\002\000\004\004\364\001" +
    "\002\000\006\002\ufffd\045\012\001\002\000\004\002\007" +
    "\001\002\000\004\002\001\001\002\000\010\002\uffd5\045" +
    "\uffd5\047\uffd5\001\002\000\010\002\uffd7\045\uffd7\047\uffd7" +
    "\001\002\000\020\017\060\025\024\027\025\032\030\033" +
    "\027\034\031\035\026\001\002\000\010\002\uffd2\045\uffd2" +
    "\047\uffd2\001\002\000\010\002\uffd6\045\uffd6\047\uffd6\001" +
    "\002\000\010\002\uffd4\045\uffd4\047\uffd4\001\002\000\006" +
    "\002\uffff\045\023\001\002\000\010\002\uffd3\045\uffd3\047" +
    "\uffd3\001\002\000\006\002\ufffe\045\023\001\002\000\010" +
    "\002\uffd1\045\uffd1\047\uffd1\001\002\000\010\002\uffd8\045" +
    "\uffd8\047\uffd8\001\002\000\016\025\024\027\025\032\030" +
    "\033\027\034\031\035\026\001\002\000\004\051\321\001" +
    "\002\000\004\046\250\001\002\000\004\051\215\001\002" +
    "\000\004\051\170\001\002\000\004\051\151\001\002\000" +
    "\004\051\032\001\002\000\004\066\033\001\002\000\004" +
    "\052\034\001\002\000\004\066\035\001\002\000\004\052" +
    "\036\001\002\000\004\063\037\001\002\000\010\063\144" +
    "\064\143\065\145\001\002\000\004\052\041\001\002\000" +
    "\004\053\042\001\002\000\004\063\037\001\002\000\006" +
    "\052\uffb9\054\uffb9\001\002\000\006\052\045\054\046\001" +
    "\002\000\004\063\037\001\002\000\004\052\047\001\002" +
    "\000\004\066\050\001\002\000\006\046\052\050\051\001" +
    "\002\000\010\002\uffc0\045\uffc0\047\uffc0\001\002\000\006" +
    "\045\054\047\055\001\002\000\004\047\136\001\002\000" +
    "\004\017\060\001\002\000\004\034\056\001\002\000\004" +
    "\046\057\001\002\000\010\002\uffbe\045\uffbe\047\uffbe\001" +
    "\002\000\004\046\061\001\002\000\004\045\063\001\002" +
    "\000\006\045\063\047\133\001\002\000\014\020\067\021" +
    "\070\022\071\023\066\024\065\001\002\000\006\045\uffed" +
    "\047\uffed\001\002\000\004\052\116\001\002\000\004\051" +
    "\112\001\002\000\004\051\107\001\002\000\004\051\100" +
    "\001\002\000\004\051\072\001\002\000\010\036\073\037" +
    "\076\040\074\001\002\000\004\050\uffe2\001\002\000\004" +
    "\050\uffe0\001\002\000\004\050\077\001\002\000\004\050" +
    "\uffe1\001\002\000\006\045\uffea\047\uffea\001\002\000\012" +
    "\057\103\060\101\061\105\062\104\001\002\000\004\050" +
    "\uffe5\001\002\000\004\050\106\001\002\000\004\050\uffe6" +
    "\001\002\000\004\050\uffe3\001\002\000\004\050\uffe4\001" +
    "\002\000\006\045\uffeb\047\uffeb\001\002\000\012\057\103" +
    "\060\101\061\105\062\104\001\002\000\004\050\111\001" +
    "\002\000\006\045\uffec\047\uffec\001\002\000\004\066\113" +
    "\001\002\000\006\046\115\050\114\001\002\000\006\045" +
    "\uffe8\047\uffe8\001\002\000\006\045\uffe9\047\uffe9\001\002" +
    "\000\004\066\117\001\002\000\004\052\120\001\002\000" +
    "\010\030\122\041\124\042\123\001\002\000\004\052\125" +
    "\001\002\000\004\052\uffdf\001\002\000\004\052\uffdd\001" +
    "\002\000\004\052\uffde\001\002\000\004\020\126\001\002" +
    "\000\004\051\127\001\002\000\012\057\103\060\101\061" +
    "\105\062\104\001\002\000\004\050\131\001\002\000\006" +
    "\045\uffe7\047\uffe7\001\002\000\006\045\uffee\047\uffee\001" +
    "\002\000\004\017\134\001\002\000\004\046\135\001\002" +
    "\000\010\002\uffef\045\uffef\047\uffef\001\002\000\004\034" +
    "\137\001\002\000\004\046\140\001\002\000\010\002\uffbf" +
    "\045\uffbf\047\uffbf\001\002\000\006\052\uffba\054\uffba\001" +
    "\002\000\010\063\147\064\146\065\150\001\002\000\010" +
    "\063\ufff8\064\ufff8\065\ufff8\001\002\000\016\006\ufffb\011" +
    "\ufffb\046\ufffb\050\ufffb\052\ufffb\054\ufffb\001\002\000\010" +
    "\063\ufff7\064\ufff7\065\ufff7\001\002\000\010\063\ufffa\064" +
    "\ufffa\065\ufffa\001\002\000\016\006\ufffc\011\ufffc\046\ufffc" +
    "\050\ufffc\052\ufffc\054\ufffc\001\002\000\010\063\ufff9\064" +
    "\ufff9\065\ufff9\001\002\000\004\066\152\001\002\000\004" +
    "\052\153\001\002\000\004\066\154\001\002\000\004\052" +
    "\155\001\002\000\004\063\037\001\002\000\006\046\160" +
    "\050\157\001\002\000\010\002\uffc6\045\uffc6\047\uffc6\001" +
    "\002\000\006\045\054\047\162\001\002\000\004\047\165" +
    "\001\002\000\004\032\163\001\002\000\004\046\164\001" +
    "\002\000\010\002\uffc4\045\uffc4\047\uffc4\001\002\000\004" +
    "\032\166\001\002\000\004\046\167\001\002\000\010\002" +
    "\uffc5\045\uffc5\047\uffc5\001\002\000\004\066\171\001\002" +
    "\000\004\052\172\001\002\000\004\066\173\001\002\000" +
    "\004\052\174\001\002\000\004\063\037\001\002\000\004" +
    "\052\176\001\002\000\004\053\177\001\002\000\004\063" +
    "\037\001\002\000\006\052\045\054\201\001\002\000\004" +
    "\052\202\001\002\000\004\066\203\001\002\000\006\046" +
    "\205\050\204\001\002\000\010\002\uffc3\045\uffc3\047\uffc3" +
    "\001\002\000\006\045\054\047\207\001\002\000\004\047" +
    "\212\001\002\000\004\033\210\001\002\000\004\046\211" +
    "\001\002\000\010\002\uffc1\045\uffc1\047\uffc1\001\002\000" +
    "\004\033\213\001\002\000\004\046\214\001\002\000\010" +
    "\002\uffc2\045\uffc2\047\uffc2\001\002\000\004\066\216\001" +
    "\002\000\004\052\217\001\002\000\004\066\220\001\002" +
    "\000\004\052\221\001\002\000\004\063\037\001\002\000" +
    "\004\052\223\001\002\000\004\053\224\001\002\000\004" +
    "\063\037\001\002\000\006\052\045\054\226\001\002\000" +
    "\004\052\227\001\002\000\004\053\230\001\002\000\006" +
    "\054\uffb7\066\231\001\002\000\006\052\uffb5\054\uffb5\001" +
    "\002\000\006\052\246\054\uffb8\001\002\000\004\054\234" +
    "\001\002\000\006\046\236\050\235\001\002\000\010\002" +
    "\uffbd\045\uffbd\047\uffbd\001\002\000\006\045\054\047\240" +
    "\001\002\000\004\047\243\001\002\000\004\035\241\001" +
    "\002\000\004\046\242\001\002\000\010\002\uffbb\045\uffbb" +
    "\047\uffbb\001\002\000\004\035\244\001\002\000\004\046" +
    "\245\001\002\000\010\002\uffbc\045\uffbc\047\uffbc\001\002" +
    "\000\004\066\247\001\002\000\006\052\uffb6\054\uffb6\001" +
    "\002\000\004\045\251\001\002\000\006\017\060\026\310" +
    "\001\002\000\004\045\253\001\002\000\004\026\254\001" +
    "\002\000\004\046\255\001\002\000\004\045\260\001\002" +
    "\000\006\045\uffcb\047\uffcb\001\002\000\006\045\260\047" +
    "\302\001\002\000\004\030\261\001\002\000\004\046\262" +
    "\001\002\000\004\045\265\001\002\000\006\045\265\047" +
    "\276\001\002\000\006\045\uffc8\047\uffc8\001\002\000\004" +
    "\031\266\001\002\000\004\046\267\001\002\000\006\045" +
    "\023\047\uffd9\001\002\000\004\047\272\001\002\000\006" +
    "\045\023\047\uffda\001\002\000\004\031\273\001\002\000" +
    "\004\046\274\001\002\000\006\045\uffc7\047\uffc7\001\002" +
    "\000\006\045\uffc9\047\uffc9\001\002\000\004\030\277\001" +
    "\002\000\004\046\300\001\002\000\006\045\uffca\047\uffca" +
    "\001\002\000\006\045\uffcc\047\uffcc\001\002\000\004\026" +
    "\303\001\002\000\004\046\304\001\002\000\004\047\305" +
    "\001\002\000\004\027\306\001\002\000\004\046\307\001" +
    "\002\000\010\002\uffce\045\uffce\047\uffce\001\002\000\004" +
    "\046\311\001\002\000\004\045\260\001\002\000\006\045" +
    "\260\047\313\001\002\000\004\026\314\001\002\000\004" +
    "\046\315\001\002\000\004\047\316\001\002\000\004\027" +
    "\317\001\002\000\004\046\320\001\002\000\010\002\uffcd" +
    "\045\uffcd\047\uffcd\001\002\000\004\066\322\001\002\000" +
    "\004\052\323\001\002\000\004\066\324\001\002\000\004" +
    "\052\325\001\002\000\004\066\326\001\002\000\004\052" +
    "\327\001\002\000\004\066\330\001\002\000\004\052\331" +
    "\001\002\000\006\043\333\044\332\001\002\000\004\046" +
    "\uffdb\001\002\000\004\046\uffdc\001\002\000\004\046\335" +
    "\001\002\000\004\045\337\001\002\000\004\045\351\001" +
    "\002\000\006\017\060\026\340\001\002\000\004\046\341" +
    "\001\002\000\006\045\023\047\uffd9\001\002\000\004\047" +
    "\343\001\002\000\004\026\344\001\002\000\004\046\345" +
    "\001\002\000\004\047\346\001\002\000\004\025\347\001" +
    "\002\000\004\046\350\001\002\000\010\002\uffcf\045\uffcf" +
    "\047\uffcf\001\002\000\004\026\352\001\002\000\004\046" +
    "\353\001\002\000\006\045\023\047\uffd9\001\002\000\004" +
    "\047\355\001\002\000\004\026\356\001\002\000\004\046" +
    "\357\001\002\000\004\047\360\001\002\000\004\025\361" +
    "\001\002\000\004\046\362\001\002\000\010\002\uffd0\045" +
    "\uffd0\047\uffd0\001\002\000\006\002\000\045\023\001\002" +
    "\000\004\005\365\001\002\000\010\006\ufff3\062\367\063" +
    "\037\001\002\000\004\006\371\001\002\000\004\006\ufff5" +
    "\001\002\000\004\006\ufff4\001\002\000\004\055\372\001" +
    "\002\000\004\007\373\001\002\000\004\056\374\001\002" +
    "\000\004\010\375\001\002\000\010\011\ufff0\062\377\063" +
    "\037\001\002\000\004\011\u0101\001\002\000\004\011\ufff2" +
    "\001\002\000\004\011\ufff1\001\002\000\004\066\u0102\001" +
    "\002\000\004\012\u0103\001\002\000\004\066\u0104\001\002" +
    "\000\004\013\u0105\001\002\000\004\066\u0106\001\002\000" +
    "\004\014\u0107\001\002\000\004\066\u0108\001\002\000\004" +
    "\015\u0109\001\002\000\004\066\u010a\001\002\000\004\016" +
    "\u010b\001\002\000\004\066\u010c\001\002\000\006\002\ufff6" +
    "\045\ufff6\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u010a\000\006\002\005\003\004\001\001\000\002\001" +
    "\001\000\024\006\015\012\017\013\010\020\013\021\007" +
    "\026\014\027\016\030\012\031\020\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\012\362\013\010\020\013\021\007" +
    "\026\014\027\016\030\012\031\020\001\001\000\002\001" +
    "\001\000\020\013\021\020\013\021\007\026\014\027\016" +
    "\030\012\031\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\035\037\001\001\000" +
    "\004\036\141\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\032\043\035\042\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\035\140\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\052\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\007\061\010\063\001\001\000\004" +
    "\010\131\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\015\074\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\017\101\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\017" +
    "\107\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\016\120" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\017\127\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\006\160\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\035\174\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\032\177\035\042\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\006\205\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\035\221\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\032\224\035\042\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\033\232\034\231" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\006\236" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\006\251\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\022\256\023" +
    "\255\001\001\000\002\001\001\000\004\023\300\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\024\262\025" +
    "\263\001\001\000\004\025\274\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\024\011\267\012" +
    "\270\013\010\020\013\021\007\026\014\027\016\030\012" +
    "\031\020\001\001\000\002\001\001\000\020\013\021\020" +
    "\013\021\007\026\014\027\016\030\012\031\020\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\022\311\023" +
    "\255\001\001\000\004\023\300\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\333\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\335\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\024\011" +
    "\341\012\270\013\010\020\013\021\007\026\014\027\016" +
    "\030\012\031\020\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\011\353\012\270\013\010\020\013" +
    "\021\007\026\014\027\016\030\012\031\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\020\013\021\020\013\021\007\026\014\027\016" +
    "\030\012\031\020\001\001\000\002\001\001\000\006\005" +
    "\365\035\367\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\004\375\035\377" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserPKM$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserPKM$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserPKM$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    LexerPKM lexer;
    private List<ErrorSintactico> erroresSintacticos = new ArrayList<>();

    public ParserPKM(LexerPKM lexer) {
        super(lexer);
        this.lexer = lexer;
    }
    
    public LexerPKM getLexer() {
        return lexer;
    }

    public List<ErrorSintactico> getErroresSintacticos() {
        return erroresSintacticos;
    }

    @Override
    public void syntax_error(Symbol cur_token){
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);
        erroresSintacticos.add(new ErrorSintactico(lexema, cur_token.left, cur_token.right, "Se esperaba otra etiqueta o valor en PKM.")); 
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token){
        String lexema = (cur_token.value != null) ? cur_token.value.toString() : symbl_name_from_id(cur_token.sym);
        erroresSintacticos.add(new ErrorSintactico(lexema, cur_token.left, cur_token.right, "Error sintáctico irrecuperable en archivo PKM."));
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserPKM$actions {
  private final ParserPKM parser;

  /** Constructor */
  CUP$ParserPKM$actions(ParserPKM parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action_part00000000(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserPKM$result;

      /* select the action based on the action number */
      switch (CUP$ParserPKM$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		RESULT = start_val;
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserPKM$parser.done_parsing();
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= metadatos estilos_bloque lista_elementos_validos 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // inicio ::= metadatos estilos_bloque 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // inicio ::= metadatos lista_elementos_validos 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inicio ::= metadatos 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // cadena_armada ::= COMILLA contenido_cadena COMILLA 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		 RESULT = c; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cadena_armada",27, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // cadena_armada ::= COMILLA COMILLA 
            {
              String RESULT =null;
		 RESULT = ""; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("cadena_armada",27, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // contenido_cadena ::= contenido_cadena TEXTO_PLANO 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		 RESULT = c + t; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido_cadena",28, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // contenido_cadena ::= contenido_cadena EMOJI 
            {
              String RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		 RESULT = c + e; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido_cadena",28, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // contenido_cadena ::= TEXTO_PLANO 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		 RESULT = t; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido_cadena",28, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // contenido_cadena ::= EMOJI 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$ParserPKM$stack.peek()).value;
		 RESULT = e; 
              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("contenido_cadena",28, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // metadatos ::= METADATA_SEP METADATA_SEP AUTHOR autor_desc FECHA VALOR_FECHA HORA VALOR_HORA DESCRIPTION valor_desc TOTAL_SECCIONES NUMERO TOTAL_PREGUNTAS NUMERO ABIERTAS NUMERO DESPLEGABLES NUMERO SELECCION NUMERO MULTIPLES NUMERO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("metadatos",1, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-21)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // autor_desc ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("autor_desc",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // autor_desc ::= cadena_armada 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("autor_desc",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // autor_desc ::= 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("autor_desc",3, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // valor_desc ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_desc",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // valor_desc ::= cadena_armada 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_desc",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // valor_desc ::= 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_desc",2, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // estilos_bloque ::= MENOR STYLE MAYOR lista_atributos_style CIERRE_ETIQUETA STYLE MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("estilos_bloque",4, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_atributos_style ::= lista_atributos_style atributo_style 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_atributos_style",5, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_atributos_style ::= atributo_style 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_atributos_style",5, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // atributo_style ::= MENOR COLOR IGUAL valor_color ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("atributo_style",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // atributo_style ::= MENOR BACKGROUND_COLOR IGUAL valor_color ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("atributo_style",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // atributo_style ::= MENOR FONT_FAMILY IGUAL tipo_fuente ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("atributo_style",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // atributo_style ::= MENOR TEXT_SIZE IGUAL NUMERO MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("atributo_style",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // atributo_style ::= MENOR TEXT_SIZE IGUAL NUMERO ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("atributo_style",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-4)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // atributo_style ::= MENOR BORDER COMA NUMERO COMA tipo_borde COMA COLOR IGUAL valor_color ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("atributo_style",6, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-10)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // valor_color ::= COLORHEX 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // valor_color ::= COLORRGB 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // valor_color ::= COLORHSL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // valor_color ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("valor_color",13, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo_fuente ::= MONO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipo_fuente ::= SANS_SERIF 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipo_fuente ::= CURSIVE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_fuente",11, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipo_borde ::= LINE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipo_borde ::= DOTTED 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // tipo_borde ::= DOUBLE_STYLE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tipo_borde",12, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // orientacion ::= VERTICAL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("orientacion",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // orientacion ::= HORIZONTAL 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("orientacion",10, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_elementos ::= lista_elementos_validos 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elementos",7, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // lista_elementos ::= 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elementos",7, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // lista_elementos_validos ::= lista_elementos_validos elemento 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elementos_validos",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_elementos_validos ::= elemento 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_elementos_validos",8, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // elemento ::= seccion 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // elemento ::= tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // elemento ::= texto_o_abierta 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // elemento ::= desplegable 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // elemento ::= seleccion 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // elemento ::= multiple 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("elemento",9, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // seccion ::= MENOR SECTION IGUAL NUMERO COMA NUMERO COMA NUMERO COMA NUMERO COMA orientacion MAYOR estilos_bloque MENOR CONTENT MAYOR lista_elementos CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA SECTION MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("seccion",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-23)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // seccion ::= MENOR SECTION IGUAL NUMERO COMA NUMERO COMA NUMERO COMA NUMERO COMA orientacion MAYOR MENOR CONTENT MAYOR lista_elementos CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA SECTION MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("seccion",14, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-22)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // tabla ::= MENOR TABLE MAYOR estilos_bloque MENOR CONTENT MAYOR lista_lineas CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA TABLE MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tabla",15, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-13)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // tabla ::= MENOR TABLE MAYOR MENOR CONTENT MAYOR lista_lineas CIERRE_ETIQUETA CONTENT MAYOR CIERRE_ETIQUETA TABLE MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("tabla",15, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-12)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // lista_lineas ::= lista_lineas linea_tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_lineas",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // lista_lineas ::= linea_tabla 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_lineas",16, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // linea_tabla ::= MENOR LINE MAYOR lista_celdas CIERRE_ETIQUETA LINE MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("linea_tabla",17, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // lista_celdas ::= lista_celdas celda 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_celdas",18, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // lista_celdas ::= celda 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_celdas",18, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // celda ::= MENOR ELEMENT MAYOR lista_elementos CIERRE_ETIQUETA ELEMENT MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("celda",19, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-6)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // texto_o_abierta ::= MENOR OPEN IGUAL NUMERO COMA NUMERO COMA cadena_armada ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("texto_o_abierta",20, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-8)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // texto_o_abierta ::= MENOR OPEN IGUAL NUMERO COMA NUMERO COMA cadena_armada MAYOR estilos_bloque CIERRE_ETIQUETA OPEN MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("texto_o_abierta",20, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-12)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // texto_o_abierta ::= MENOR OPEN IGUAL NUMERO COMA NUMERO COMA cadena_armada MAYOR CIERRE_ETIQUETA OPEN MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("texto_o_abierta",20, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-11)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // desplegable ::= MENOR DROP IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA NUMERO ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("desplegable",21, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // desplegable ::= MENOR DROP IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA NUMERO MAYOR estilos_bloque CIERRE_ETIQUETA DROP MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("desplegable",21, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-18)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // desplegable ::= MENOR DROP IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA NUMERO MAYOR CIERRE_ETIQUETA DROP MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("desplegable",21, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-17)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // seleccion ::= MENOR SELECT IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA NUMERO ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("seleccion",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-14)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // seleccion ::= MENOR SELECT IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA NUMERO MAYOR estilos_bloque CIERRE_ETIQUETA SELECT MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("seleccion",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-18)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // seleccion ::= MENOR SELECT IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA NUMERO MAYOR CIERRE_ETIQUETA SELECT MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("seleccion",22, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-17)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // multiple ::= MENOR MULTIPLE IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA LLA_IZQ lista_respuestas LLA_DER ETIQUETA_AUTOCIERRE 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple",23, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-16)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // multiple ::= MENOR MULTIPLE IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA LLA_IZQ lista_respuestas LLA_DER MAYOR estilos_bloque CIERRE_ETIQUETA MULTIPLE MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple",23, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-20)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // multiple ::= MENOR MULTIPLE IGUAL NUMERO COMA NUMERO COMA cadena_armada COMA LLA_IZQ lista_opciones LLA_DER COMA LLA_IZQ lista_respuestas LLA_DER MAYOR CIERRE_ETIQUETA MULTIPLE MAYOR 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("multiple",23, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-19)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // lista_opciones ::= lista_opciones COMA cadena_armada 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_opciones",24, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // lista_opciones ::= cadena_armada 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_opciones",24, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // lista_respuestas ::= respuestas_validas 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_respuestas",25, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // lista_respuestas ::= 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("lista_respuestas",25, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // respuestas_validas ::= respuestas_validas COMA NUMERO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("respuestas_validas",26, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.elementAt(CUP$ParserPKM$top-2)), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // respuestas_validas ::= NUMERO 
            {
              Object RESULT =null;

              CUP$ParserPKM$result = parser.getSymbolFactory().newSymbol("respuestas_validas",26, ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPKM$stack.peek()), RESULT);
            }
          return CUP$ParserPKM$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserPKM$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserPKM$do_action(
    int                        CUP$ParserPKM$act_num,
    java_cup.runtime.lr_parser CUP$ParserPKM$parser,
    java.util.Stack            CUP$ParserPKM$stack,
    int                        CUP$ParserPKM$top)
    throws java.lang.Exception
    {
              return CUP$ParserPKM$do_action_part00000000(
                               CUP$ParserPKM$act_num,
                               CUP$ParserPKM$parser,
                               CUP$ParserPKM$stack,
                               CUP$ParserPKM$top);
    }
}

}
