
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int HORIZONTAL = 21;
  public static final int SELECT_QUESTION = 7;
  public static final int IDENTIFICADOR = 78;
  public static final int MENOR_IGUAL = 59;
  public static final int TABLE = 3;
  public static final int COR_IZQ = 69;
  public static final int COLOR_HEX = 79;
  public static final int POTENCIA = 54;
  public static final int EMOJI = 49;
  public static final int MAYOR = 56;
  public static final int SANS_SERIF = 23;
  public static final int DROP_QUESTION = 6;
  public static final int BLUE = 29;
  public static final int YELLOW = 33;
  public static final int DIFERENTE = 61;
  public static final int ELEMENTS = 14;
  public static final int DRAW = 40;
  public static final int WHITE = 35;
  public static final int PAR_DER = 68;
  public static final int LLA_IZQ = 71;
  public static final int OPEN_QUESTION = 5;
  public static final int POR = 52;
  public static final int BLACK = 34;
  public static final int DOUBLE = 27;
  public static final int NOT = 62;
  public static final int TEXT = 4;
  public static final int DOS_PUNTOS = 74;
  public static final int PURPLE = 31;
  public static final int WIDTH = 9;
  public static final int PUNTO_COMA = 75;
  public static final int IGUALDAD = 60;
  public static final int STYLES = 15;
  public static final int TYPE_SPECIAL = 38;
  public static final int NUMBER = 77;
  public static final int COMA = 73;
  public static final int MODULO = 55;
  public static final int TYPE_NUMBER = 36;
  public static final int CURSIVE = 24;
  public static final int MONO = 22;
  public static final int WHILE = 43;
  public static final int DO = 44;
  public static final int FOR = 45;
  public static final int DIV = 53;
  public static final int COMODIN = 66;
  public static final int ORIENTATION = 13;
  public static final int ELSE = 42;
  public static final int MENOS = 51;
  public static final int MULTIPLE_QUESTION = 8;
  public static final int MENOR = 57;
  public static final int MAS = 50;
  public static final int COLOR_RGB = 80;
  public static final int TEXTO_PLANO = 48;
  public static final int CORRECT = 19;
  public static final int CONTENT = 17;
  public static final int PAR_IZQ = 67;
  public static final int EOF = 0;
  public static final int PUNTO = 76;
  public static final int VERTICAL = 20;
  public static final int LINE = 25;
  public static final int COR_DER = 70;
  public static final int LABEL = 16;
  public static final int IN = 46;
  public static final int COMILLA = 47;
  public static final int OR = 64;
  public static final int SKY = 32;
  public static final int error = 1;
  public static final int LLA_DER = 72;
  public static final int IF = 41;
  public static final int DOTTED = 26;
  public static final int HEIGHT = 10;
  public static final int RED = 28;
  public static final int ASIGNACION = 65;
  public static final int COLOR_HSL = 81;
  public static final int POINTY = 12;
  public static final int OPTIONS = 18;
  public static final int POINTX = 11;
  public static final int TYPE_STRING = 37;
  public static final int AND = 63;
  public static final int UMINUS = 82;
  public static final int WHO_IS_THAT_POKEMON = 39;
  public static final int MAYOR_IGUAL = 58;
  public static final int SECTION = 2;
  public static final int GREEN = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SECTION",
  "TABLE",
  "TEXT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "WIDTH",
  "HEIGHT",
  "POINTX",
  "POINTY",
  "ORIENTATION",
  "ELEMENTS",
  "STYLES",
  "LABEL",
  "CONTENT",
  "OPTIONS",
  "CORRECT",
  "VERTICAL",
  "HORIZONTAL",
  "MONO",
  "SANS_SERIF",
  "CURSIVE",
  "LINE",
  "DOTTED",
  "DOUBLE",
  "RED",
  "BLUE",
  "GREEN",
  "PURPLE",
  "SKY",
  "YELLOW",
  "BLACK",
  "WHITE",
  "TYPE_NUMBER",
  "TYPE_STRING",
  "TYPE_SPECIAL",
  "WHO_IS_THAT_POKEMON",
  "DRAW",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "COMILLA",
  "TEXTO_PLANO",
  "EMOJI",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POTENCIA",
  "MODULO",
  "MAYOR",
  "MENOR",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "IGUALDAD",
  "DIFERENTE",
  "NOT",
  "AND",
  "OR",
  "ASIGNACION",
  "COMODIN",
  "PAR_IZQ",
  "PAR_DER",
  "COR_IZQ",
  "COR_DER",
  "LLA_IZQ",
  "LLA_DER",
  "COMA",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "PUNTO",
  "NUMBER",
  "IDENTIFICADOR",
  "COLOR_HEX",
  "COLOR_RGB",
  "COLOR_HSL",
  "UMINUS"
  };
}

